# Generated by Django 4.0.3 on 2022-06-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_option_one_alter_question_option_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_image',
            field=models.ImageField(blank=True, upload_to='quiz_image/'),
        ),
    ]
